steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'export']
  - name: gcr.io/pour-over-guides/firebase
    args: ['deploy', '--project=$_FIREBASE_PROJECT_ID', '--only=hosting']
